version: '3'

services:
  postgres:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: sh -c "npm run migration:run && node dist/server.js"
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres:
