version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}       
      POSTGRES_USER: ${DB_USER}     
      POSTGRES_PASSWORD: ${DB_PASS} 
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"] 
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
    command:
      - sh
      - -c
      - "node ./node_modules/typeorm/cli.js migration:run -d dist/config/data-source.js && node dist/server.js"

volumes:
  db-data: