name: Monorepo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:14
        env:
          POSTGRES_USER: example
          POSTGRES_PASSWORD: example
          POSTGRES_DB: exampledb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Esperar DB ficar pronto
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 && break
            sleep 2
          done

      - name: Setup Node for Backend
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Install Backend deps
        run: npm ci
        working-directory: backend

      - name: Run Backend migrations
        run: npm run migration: generate
        run: npm run migration: run  
        working-directory: backend

      - name: Test Backend
        run: npm test
        working-directory: backend

      - name: Setup Node for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Install Frontend deps
        run: npm ci
        working-directory: frontend

      - name: Test Frontend
        run: npm test
        working-directory: frontend

      - name: Build Frontend
        run: npm run build
        working-directory: frontend
